version: '3'

services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - TZ=America/Sao_Paulo
        ports:
            - '5442:5432'

    php:
        build: docker/php-fpm
        ports:
            - '9002:9000'
        depends_on:
            - postgres
        volumes:
            - .:/var/www/url_shortner/

    nginx:
        build: docker/nginx
        ports:
            - '8080:80'
        depends_on:
            - php
        volumes:
            - .:/var/www/url_shortner/
